version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sotodelprior_db
    restart: always
    environment:
      POSTGRES_USER: soto_user
      POSTGRES_PASSWORD: soto_password
      POSTGRES_DB: sotodelprior
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
